import Triple from "./Triple.js";
import SPARQL from "./sparql.js";
window.PARSER = /*
 * Generated by PEG.js 0.10.0.
 *
 * http://pegjs.org/
 */
    (function() {

return {
    SyntaxError: peg$SyntaxError,
    DefaultTracer: peg$DefaultTracer,
    parse:       peg$parse
};
})();